/**
 * Catálogo de textos editables (etiquetas en español para el panel).
 * Las claves coinciden con js/i18n.js (data-i18n / data-i18n-html).
 */
(function (g) {
  g.TT_ADMIN_CATALOG = {
    langs: [
      { id: "es", label: "Español" },
      { id: "en", label: "English" },
      { id: "nl", label: "Nederlands" },
      { id: "fr", label: "Français" },
      { id: "de", label: "Deutsch" },
    ],
    galleryCategories: [
      { id: "bordados", label: "Bordados" },
      { id: "dibujos", label: "Dibujos" },
      { id: "instalacion", label: "Instalación" },
      { id: "plasticina", label: "Plasticina" },
      { id: "telar", label: "Telar" },
      { id: "volumen", label: "Volumen" },
    ],
    textGroups: [
      {
        id: "nav-footer",
        label: "Menú, tienda y pie de página",
        fields: [
          { key: "brand.tag", label: "Subtítulo bajo el logo (ej. taller textil)", html: false },
          { key: "nav.home", label: "Enlace: Inicio", html: false },
          { key: "nav.studio", label: "Enlace: Taller", html: false },
          { key: "nav.kit", label: "Enlace: Kit de telar", html: false },
          { key: "nav.about", label: "Enlace: Acerca de mí", html: false },
          { key: "nav.lines", label: "Enlace: Líneas", html: false },
          { key: "nav.work", label: "Enlace: Obra", html: false },
          { key: "nav.contact", label: "Enlace: Contacto", html: false },
          { key: "shop.online", label: "Botón: Tienda online", html: false },
          { key: "footer.home", label: "Pie: Inicio", html: false },
          { key: "footer.ig", label: "Pie: Instagram", html: false },
          { key: "footer.top", label: "Pie: Volver arriba", html: false },
          { key: "footer.visits", label: "Pie: texto «Visitas»", html: false },
          { key: "wa.label", label: "Etiqueta del botón flotante WhatsApp", html: false },
        ],
      },
      {
        id: "home-hero",
        label: "Inicio — portada principal",
        fields: [
          { key: "hero.kicker", label: "Línea pequeña (nombre · ciudad)", html: false },
          { key: "hero.headline", label: "Título principal", html: false },
          { key: "hero.lead", label: "Texto destacado bajo el título", html: false },
          { key: "hero.ctaWork", label: "Botón: Ver obra", html: false },
          { key: "hero.ctaIg", label: "Botón: Instagram", html: false },
          { key: "hero.caption", label: "Línea bajo el carrusel (textil · bordado…)", html: false },
        ],
      },
      {
        id: "marquee",
        label: "Inicio — franja animada",
        fields: [
          { key: "marquee.a", label: "Franja — fragmento 1", html: false },
          { key: "marquee.b", label: "Franja — fragmento 2", html: false },
          { key: "marquee.c", label: "Franja — fragmento 3", html: false },
          { key: "marquee.d", label: "Franja — fragmento 4 (ciudad)", html: false },
        ],
      },
      {
        id: "taller",
        label: "Página Taller",
        fields: [
          { key: "about.title", label: "Título de la sección", html: false },
          { key: "about.lead", label: "Primer párrafo (admite negritas HTML)", html: true },
          { key: "about.p2", label: "Segundo párrafo", html: false },
          { key: "studio.subnavIntro", label: "Submenú: Presentación", html: false },
          { key: "studio.photosTitle", label: "Título: El estudio", html: false },
          { key: "studio.photosIntro", label: "Texto intro de las fotos del estudio", html: false },
          { key: "pillar1.title", label: "Tarjeta 1 — título", html: false },
          { key: "pillar1.desc", label: "Tarjeta 1 — descripción", html: false },
          { key: "pillar2.title", label: "Tarjeta 2 — título", html: false },
          { key: "pillar2.desc", label: "Tarjeta 2 — descripción", html: false },
          { key: "pillar3.title", label: "Tarjeta 3 — título", html: false },
          { key: "pillar3.desc", label: "Tarjeta 3 — descripción", html: false },
          { key: "pillar4.title", label: "Tarjeta 4 — título", html: false },
          { key: "pillar4.desc", label: "Tarjeta 4 — descripción", html: false },
        ],
      },
      {
        id: "kit",
        label: "Página Kit de telar",
        fields: [
          { key: "studio.kitTitle", label: "Título", html: false },
          { key: "studio.kitLead", label: "Entradilla", html: false },
          { key: "studio.kitBody", label: "Cuerpo de texto", html: false },
          { key: "studio.kitManualNote", label: "Nota del manual", html: false },
        ],
      },
      {
        id: "about-me",
        label: "Página Acerca de mí",
        fields: [
          { key: "studio.aboutTitle", label: "Título", html: false },
          { key: "studio.bio", label: "Biografía (párrafos HTML)", html: true },
          { key: "studio.cvLink", label: "Texto del enlace al CV", html: false },
          { key: "studio.cvPhotoLink", label: "Texto del enlace al retrato", html: false },
        ],
      },
      {
        id: "lineas-obra",
        label: "Líneas y galería Obra",
        fields: [
          { key: "collections.title", label: "Título sección líneas", html: false },
          { key: "collections.intro", label: "Intro galería Obra", html: false },
          { key: "gallery.title", label: "Título página Obra", html: false },
          { key: "gallery.hintHtml", label: "Ayuda bajo el título (permite HTML)", html: true },
          { key: "gallery.pieces", label: "Palabra «piezas» (contador)", html: false },
          { key: "lineas.hint", label: "Texto página Líneas", html: false },
          { key: "cat.all", label: "Filtro: Todo", html: false },
          { key: "cat.bordados", label: "Filtro: Bordados", html: false },
          { key: "cat.dibujos", label: "Filtro: Dibujos", html: false },
          { key: "cat.instalacion", label: "Filtro: Instalación", html: false },
          { key: "cat.plasticina", label: "Filtro: Plasticina", html: false },
          { key: "cat.telar", label: "Filtro: Telar", html: false },
          { key: "cat.volumen", label: "Filtro: Volumen", html: false },
          { key: "lightbox.detail", label: "Lightbox: enlace a la ficha", html: false },
        ],
      },
      {
        id: "contact",
        label: "Contacto",
        fields: [
          { key: "contact.title", label: "Título", html: false },
          { key: "contact.lead", label: "Entradilla", html: false },
          { key: "contact.shopNote", label: "Nota tienda (HTML)", html: true },
          { key: "contact.location", label: "Línea de ubicación", html: false },
          { key: "contact.cardLabel", label: "Etiqueta tarjeta redes", html: false },
          { key: "contact.instagramBtn", label: "Botón Instagram", html: false },
          { key: "contact.waBtn", label: "Botón WhatsApp", html: false },
        ],
      },
      {
        id: "seo",
        label: "SEO — títulos y descripciones (Google)",
        fields: [
          { key: "meta.title", label: "Título pestaña — Inicio", html: false },
          { key: "meta.description", label: "Descripción — Inicio", html: false },
          { key: "meta.titleTaller", label: "Título — Taller", html: false },
          { key: "meta.descTaller", label: "Descripción — Taller", html: false },
          { key: "meta.titleKit", label: "Título — Kit", html: false },
          { key: "meta.descKit", label: "Descripción — Kit", html: false },
          { key: "meta.titleAbout", label: "Título — Acerca de mí", html: false },
          { key: "meta.descAbout", label: "Descripción — Acerca de mí", html: false },
          { key: "meta.titleLineas", label: "Título — Líneas", html: false },
          { key: "meta.descLineas", label: "Descripción — Líneas", html: false },
          { key: "meta.titleObra", label: "Título — Obra", html: false },
          { key: "meta.descObra", label: "Descripción — Obra", html: false },
          { key: "meta.titleContact", label: "Título — Contacto", html: false },
          { key: "meta.descContact", label: "Descripción — Contacto", html: false },
        ],
      },
    ],
  };
})(typeof window !== "undefined" ? window : globalThis);
